"""teste

Revision ID: 5d5321812467
Revises: 
Create Date: 2026-02-28 10:15:14.416455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5321812467'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_line',
    sa.Column('knr', sa.String(length=20), nullable=False),
    sa.Column('takt', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=10), nullable=False),
    sa.Column('lfdnr_sequence', sa.String(length=50), nullable=False),
    sa.Column('lane', sa.String(length=20), nullable=False),
    sa.Column('spj', sa.String(length=10), nullable=False),
    sa.Column('werk', sa.String(length=10), nullable=False),
    sa.Column('knr_fx4pd', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('knr')
    )
    op.create_index(op.f('ix_assembly_line_knr_fx4pd'), 'assembly_line', ['knr_fx4pd'], unique=False)
    op.create_index(op.f('ix_assembly_line_lane'), 'assembly_line', ['lane'], unique=False)
    op.create_index(op.f('ix_assembly_line_takt'), 'assembly_line', ['takt'], unique=False)
    op.create_table('forecast',
    sa.Column('partnumber', sa.String(length=50), nullable=False),
    sa.Column('num_reg_circ', sa.String(length=20), nullable=False),
    sa.Column('takt', sa.String(length=10), nullable=False),
    sa.Column('rack', sa.String(length=10), nullable=False),
    sa.Column('lb_balance', sa.Float(), nullable=False),
    sa.Column('total_theoretical_qty', sa.Float(), nullable=False),
    sa.Column('qty_for_restock', sa.Float(), nullable=False),
    sa.Column('qty_per_box', sa.Float(), nullable=False),
    sa.Column('qty_max_box', sa.Float(), nullable=False),
    sa.Column('knr_fx4pd', sa.String(length=50), nullable=False),
    sa.Column('qty_usage', sa.Float(), nullable=False),
    sa.Column('qty_unit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('partnumber', 'takt', 'rack', 'knr_fx4pd')
    )
    op.create_index(op.f('ix_forecast_knr_fx4pd'), 'forecast', ['knr_fx4pd'], unique=False)
    op.create_index(op.f('ix_forecast_partnumber'), 'forecast', ['partnumber'], unique=False)
    op.create_index(op.f('ix_forecast_rack'), 'forecast', ['rack'], unique=False)
    op.create_index(op.f('ix_forecast_takt'), 'forecast', ['takt'], unique=False)
    op.create_table('fx4pd',
    sa.Column('knr_fx4pd', sa.String(length=255), nullable=False),
    sa.Column('partnumber', sa.String(length=255), nullable=False),
    sa.Column('qty_usage', sa.Float(), nullable=False),
    sa.Column('qty_unit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('knr_fx4pd', 'partnumber')
    )
    op.create_table('requests_made',
    sa.Column('partnumber', sa.String(length=255), nullable=False),
    sa.Column('supply_area', sa.String(length=255), nullable=False),
    sa.Column('num_reg_circ', sa.String(length=255), nullable=False),
    sa.Column('qty_to_request', sa.Float(), nullable=False),
    sa.Column('qty_boxes_to_request', sa.Float(), nullable=False),
    sa.Column('takt', sa.String(length=255), nullable=False),
    sa.Column('rack', sa.String(length=255), nullable=False),
    sa.Column('num_shipment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('partnumber', 'supply_area')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests_made')
    op.drop_table('fx4pd')
    op.drop_index(op.f('ix_forecast_takt'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_rack'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_partnumber'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_knr_fx4pd'), table_name='forecast')
    op.drop_table('forecast')
    op.drop_index(op.f('ix_assembly_line_takt'), table_name='assembly_line')
    op.drop_index(op.f('ix_assembly_line_lane'), table_name='assembly_line')
    op.drop_index(op.f('ix_assembly_line_knr_fx4pd'), table_name='assembly_line')
    op.drop_table('assembly_line')
    # ### end Alembic commands ###
